function audioFiltered = bandpass_filter_audio(audioData, audioBandFilter, audioFs)
    bpFilt = designfilt('bandpassiir', ...
        'FilterOrder',         8, ...
        'HalfPowerFrequency1', audioBandFilter(1), ...
        'HalfPowerFrequency2', audioBandFilter(2), ...
        'SampleRate',          audioFs);
    audioFiltered = filtfilt(bpFilt, audioData);
    fprintf('[INFO] Applied bandpass filter: %.0f-%.0f Hz\n', ...
        audioBandFilter(1), audioBandFilter(2));
end